# Server configuration
bind_address=127.0.0.1
http_port=8080
www_root=./www/
index_file=index.html
enable_logging=true
directory_listing=true
log_path=access.log
enable_log_rotation=true
log_max_size=10M
log_max_files=5
enable_https=false
cert=server-cert.pem
key=server-key.pem
